// 本文件集中维护前端调用后端 API 的路径常量。
// 它不发起请求，只提供 Rust 后端已实现路径和前端规划路径。
// 拆出路径表后，客户端模块可以按领域组合，避免入口文件继续膨胀。
// 新增接口时先确认后端路由，再把路径放入对应常量组。

export const rustApiPaths = {
  register: '/api/auth/register',
  login: '/api/auth/login',
  captcha: '/api/auth/captcha',
  emailCode: '/api/auth/email-code',
  refresh: '/api/auth/refresh',
  logout: '/api/auth/logout',
  authSecurity: '/api/auth/security',
  overview: '/api/admin/access-operations/summary',
  accessOperationsSummary: '/api/admin/access-operations/summary',
  accessOperationsLedgerRanking: '/api/admin/access-operations/ledger-ranking',
  accessOperationsPlatformMetrics: '/api/admin/access-operations/platform-metrics',
  accessOperationsSettings: '/api/admin/access-operations/settings',
  accessOperationsProbe: '/api/admin/access-operations/probe',
  accessRouting: '/api/admin/access-routing',
  userInviteCodes: '/api/user/invite-codes',
  accessNodes: '/api/admin/access-nodes',
  accessNodeInstallGuide: '/api/admin/access-nodes/install-guide',
  accessNodeOneClickInstall: '/api/admin/access-nodes/one-click-install',
  deploymentTasks: '/api/admin/deployment-tasks',
  accessLines: '/api/admin/access-lines',
  accessEntries: '/api/admin/access-entries',
  accessEntryExitBindings: '/api/admin/access-entry-exit-bindings',
  exitResources: '/api/admin/exit-resources',
  exitEndpoints: '/api/admin/exit-endpoints',
  exitPools: '/api/admin/exit-pools',
  lineGroups: '/api/admin/line-groups',
  subscriptionRuleSets: '/api/admin/subscription-rule-sets',
  // 监控中心·节点业务流量：汇总（?from_ms&to_ms）与单节点趋势（/{node_id}/trend?...&bucket=）同前缀。
  monitorNodeTraffic: '/api/admin/monitor/node-traffic',
  plans: '/api/plans',
  salesLanding: '/api/sales-landing',
  adminPlans: '/api/admin/plans',
  adminSalesLanding: '/api/admin/sales-landing',
  adminPlanLineGroups: '/api/admin/plans/{planId}/line-groups',
  adminUserTrafficLogs: '/api/admin/users/{id}/traffic-logs',
  adminUserDevices: '/api/admin/users/{id}/devices',
  subscription: '/api/user/subscription',
  userUsage: '/api/user/usage',
  resetSubscriptionToken: '/api/user/subscription/token/reset',
  changePasswordSendCode: '/api/user/password/send-code',
  changePassword: '/api/user/password',
  subscriptionDownload: '/sub/{token}',
} as const;

export const plannedApiPaths = {
  adminAuditLogs: '/api/admin/audit-logs',
  adminUsers: '/api/admin/users',
  adminUsersBatchDelete: '/api/admin/users/batch-delete',
  adminUserSubscription: '/api/admin/users/{id}/subscription',
  adminUserSubscriptionTokenReset: '/api/admin/users/{id}/subscription-token/reset',
  adminUserResetPassword: '/api/admin/users/{id}/reset-password',
  adminOrders: '/api/admin/orders',
  adminRedeemCodes: '/api/admin/redeem-codes',
  adminInviteCodes: '/api/admin/invite-codes',
  adminAuthSecurity: '/api/admin/auth-security',
  adminPaymentSettings: '/api/admin/payment-settings',
  adminBackupConfig: '/api/admin/backup/config',
  adminBackupTestProvision: '/api/admin/backup/test-and-provision',
  adminBackupRunNow: '/api/admin/backup/run-now',
  adminBackupState: '/api/admin/backup/state',
  adminSubscriptionSettings: '/api/admin/subscription-settings',
  paymentChannels: '/api/payment/channels',
  userOrders: '/api/orders',
  redeem: '/api/redeem',
} as const;
