#!/usr/bin/env bash
# 用途：校验真实协议矩阵私有环境文件是否满足运行要求。
# 用途：入口脚本解析参数、加载 env，并调用 helper 中的校验函数。
# 用途：输出只包含变量名、协议名与粗粒度状态，避免泄露私密值。
set -euo pipefail
IFS=$'\n\t'
set +x

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BASE_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
VALIDATION_LIB="${SCRIPT_DIR}/lib/check-real-protocol-matrix-env/validation.sh"
cd "$BASE_DIR"

ENV_FILE="${XRAYC_REAL_PROTOCOL_MATRIX_ENV_FILE:-${XRAYC_REAL_RELEASE_ENV_FILE:-}}"
PROTOCOLS_ARG=""
MODE_ARG=""
PROTOCOLS="${REAL_PROTOCOL_MATRIX_PROTOCOLS:-socks,http,vless,trojan,shadowsocks,hy2}"
MATRIX_MODE="${REAL_RELEASE_MATRIX_MODE:-relay}"
ALLOW_MISSING_ENDPOINTS=0
FAILURES=0

# shellcheck disable=SC1090
. "$VALIDATION_LIB"

usage() {
  cat <<'USAGE'
Usage:
  bash scripts/check-real-protocol-matrix-env.sh --env-file /private/real-protocol-matrix.env

Options:
  --env-file PATH      Private env file generated by prepare-real-protocol-matrix-assets.sh.
                       Defaults to XRAYC_REAL_PROTOCOL_MATRIX_ENV_FILE, then
                       XRAYC_REAL_RELEASE_ENV_FILE.
  --protocols LIST     Comma-separated protocol list. Default:
                       socks,http,vless,trojan,shadowsocks,hy2.
  --mode MODE          Matrix execution mode: relay or direct. Relay creates
                       the client proxy at runtime from the current private
                       inventory; direct requires CLIENT_PROXY_URL_* upfront.
  --allow-missing-endpoints
                       Permit EXIT_ENDPOINT_ID_* to be absent during the
                       pre-prepare relay env check. A strict check must run
                       after prepare-real-protocol-matrix-endpoints.sh.
  -h, --help           Show this help.

The script reports only variable names, protocol names, and coarse status. It
does not print real hosts, IPs, passwords, tokens, proxy URLs, database URLs, or
raw provider URLs.
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --env-file)
      ENV_FILE="${2:-}"
      shift 2
      ;;
    --protocols)
      PROTOCOLS_ARG="${2:-}"
      shift 2
      ;;
    --mode)
      MODE_ARG="${2:-}"
      shift 2
      ;;
    --allow-missing-endpoints)
      ALLOW_MISSING_ENDPOINTS=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ -z "$ENV_FILE" ]]; then
  report "XRAYC_REAL_PROTOCOL_MATRIX_ENV_FILE or --env-file is required"
elif [[ ! -f "$ENV_FILE" ]]; then
  report "private env file is missing"
fi

if ! command -v python3 >/dev/null 2>&1; then
  report "local python3 command is missing"
fi

if [[ "$FAILURES" -gt 0 ]]; then
  printf 'real-protocol-matrix-env: blocked with %s issue(s)\n' "$FAILURES" >&2
  exit 2
fi

set -a
# shellcheck disable=SC1090
. "$ENV_FILE"
set +a

PROTOCOLS="${PROTOCOLS_ARG:-${REAL_PROTOCOL_MATRIX_PROTOCOLS:-$PROTOCOLS}}"
MATRIX_MODE="${MODE_ARG:-${REAL_RELEASE_MATRIX_MODE:-$MATRIX_MODE}}"
case "$MATRIX_MODE" in
  relay|direct) ;;
  *) report "REAL_RELEASE_MATRIX_MODE must be relay or direct" ;;
esac

require_url_scheme BASE_URL
check_inventory
if [[ "$MATRIX_MODE" == "direct" ]]; then
  require_any_value "SUB_TOKEN or SUBSCRIPTION_URL" SUB_TOKEN SUBSCRIPTION_URL
  if [[ -n "${SUBSCRIPTION_URL:-}" ]]; then
    require_url_scheme SUBSCRIPTION_URL
  fi
  require_value USER_ACCESS_TOKEN
  require_value AGENT_TOKEN
  require_uuid ACCESS_NODE_ID
  require_uuid ACCESS_LINE_ID
  require_uuid EXIT_ENDPOINT_ID
  require_url_scheme CLIENT_PROXY_URL
  require_public_ip EXPECTED_EXIT_IP
  require_value EXPECTED_ACCESS_SERVERS
else
  require_value ADMIN_LOGIN_ACCOUNT
  require_value ADMIN_LOGIN_PASSWORD
  require_value USER_LOGIN_ACCOUNT
  require_value USER_LOGIN_PASSWORD
  require_url_scheme DATABASE_URL
  require_deploy_token_source
fi

IFS=',' read -r -a protocol_items <<< "$PROTOCOLS"
if [[ "${#protocol_items[@]}" -eq 0 ]]; then
  report "REAL_PROTOCOL_MATRIX_PROTOCOLS is empty"
fi

for item in "${protocol_items[@]}"; do
  protocol="$(normalize_protocol "$item")"
  if [[ -z "$protocol" ]]; then
    report "REAL_PROTOCOL_MATRIX_PROTOCOLS contains an empty item"
    continue
  fi
  require_protocol_group "$protocol"
done

if [[ "$FAILURES" -gt 0 ]]; then
  printf 'real-protocol-matrix-env: blocked with %s issue(s)\n' "$FAILURES" >&2
  exit 2
fi

echo "real-protocol-matrix-env: passed"
